name: money_management_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_form_builder: ^10.1.0
  form_builder_image_picker: ^4.3.1
  form_builder_validators: ^11.2.0
  go_router: ^16.1.0
  freezed_annotation: ^2.2.0
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_storage: any
  cloud_firestore: ^6.0.0
  flutter_riverpod: ^2.6.1
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  hive_generator: ^2.0.1
  riverpod_generator: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/logo.png"

  image_path: "assets/images/logo.png"
