// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt6BPTERhDzQQeyn0WEu6LKRd6oywtB_Q',
    appId: '1:52154267564:web:22a05ad85ce5820fb4ac09',
    messagingSenderId: '52154267564',
    projectId: 'money-management-app-82252',
    authDomain: 'money-management-app-82252.firebaseapp.com',
    storageBucket: 'money-management-app-82252.firebasestorage.app',
    measurementId: 'G-TYMHZXTQYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1rlbP8TPkco7Wa7VminT9R91rTb9WXUs',
    appId: '1:52154267564:android:4659fce2f0253c80b4ac09',
    messagingSenderId: '52154267564',
    projectId: 'money-management-app-82252',
    storageBucket: 'money-management-app-82252.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcq_x4p16OzEWd7hD6o8pUhsKxMVloDnQ',
    appId: '1:52154267564:ios:bcd64e12d68a030ab4ac09',
    messagingSenderId: '52154267564',
    projectId: 'money-management-app-82252',
    storageBucket: 'money-management-app-82252.firebasestorage.app',
    iosBundleId: 'com.example.moneyManagementApp',
  );
}
